name: first_app_new
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animate_do: ^3.0.2
  socket_io_client: ^2.0.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^8.0.0
  flutter_animate: ^4.1.1+1
  google_nav_bar: ^5.0.7
  fluttertoast: ^8.2.12
  glassmorphism: ^3.0.0
  location: ^6.0.2
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  http_parser: ^4.0.2
  image_picker: ^1.0.7
  equatable: 2.0.5
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  sizer: ^2.0.15
  google_maps_flutter: ^2.5.3  
  flutter_dotenv: ^5.1.0
  json_annotation: ^4.8.1
  web_socket_channel: ^2.4.0
  intl: ^0.19.0
  flutter_rating_bar: ^4.0.1        
  connectivity_plus: ^6.1.4
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true  # Add this line for localizations generation
  uses-material-design: true

  assets:
    - .env
    - assets/facebook.png
    - assets/whatsapp.png
    - assets/email.png 
    - assets/icons/ios.svg
    - assets/icons/code.svg
    - assets/images/img_3d_food_icon_by.png
    - assets/images/img_3d_food_icon_by_195x163.png
    - assets/images/img_3d_food_icon_by_279x292.png
    - assets/images/img_3d_food_icon_by_146x158.png
    - assets/images/img_3d_food_icon_by_213x216.png
    - assets/images/logoBw.png
    - assets/default_profile.jpg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsRegular.ttf
